FROM python:3

WORKDIR /app

ENV     SERVICE_NAME 'djangonetes-dev'
ENV     SERVICE_VERSION ''

ENV     DJANGO_SECRET_KEY 'dev'
ENV     DJANGO_DEBUG 1
ENV     DJANGO_COMPOSE 0
ENV     DJANGO_MODE_FREE_HOST 1

ENV     FORCE_SCRIPT_NAME '/dev'
ENV     WHITENOISE_STATIC_PREFIX '/static/'

ADD    ./requirements.txt   /app/
RUN    pip install -r requirements.txt

ADD    ./config    /app/config/
ADD    ./service    /app/service/


ADD    ./gunicorn       /app/gunicorn/
ADD    ./manage.py      /app/

RUN     mkdir -p static
RUN     mkdir -p .static_root

RUN     python manage.py collectstatic

# when you add your database you have to change below part
RUN     python manage.py migrate
RUN     python manage.py create_admin

CMD ["gunicorn", "config.wsgi", "-c", "gunicorn/prod.py"]
