apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: djangonetes-dev-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/add-base-url : "true"
spec:
  rules:
  - host: kube.djangonetes.io
    http:
      paths:
      - path: /dev(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: djangonetes.dev
            port:
              number: 80
